name: Compile Go Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Compile
      run: |
        go build -v ./...

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: gdrive-build
        path: |
          ./gdrive # replace with your actual binary path
